"""
Phonetic blocking strategy (strategy_phonetic.py)
===================================================

Distinct signal from the six other strategies in this pipeline (token
overlap, TF-IDF cosine, MinHash/LSH, sentence embeddings, sorted
neighborhood, DeepBlocker-style tuple embeddings, rapidfuzz string
similarity): here we block on the *phonetic encoding* (Soundex +
Double Metaphone, via `jellyfish`) of the manufacturer/brand name, so
that brand variants and typos that don't share a token or a high
string-similarity score still land in the same bucket -- e.g.
"Intuit" vs "Intuit Inc" vs a misspelled "Intuet" all normalize to the
same Soundex code.

Why phonetic and not just fuzzy string matching: rapidfuzz (already
covered by strategy_fuzzy.py) scores *edit distance / token overlap*,
which is good at typos but not at true phonetic spelling variants
(e.g. "Encore" vs "Encor", "Sierra" vs "Ciera") where characters
differ but the pronunciation doesn't. Soundex/Metaphone map those to
identical codes, giving the learned ensemble scorer a genuinely
different feature axis to combine with the others.

manufacturer coverage:
  - TableA: fully populated.
  - TableB: sparse, only ~356/3226 non-null.
For TableB rows with a null manufacturer, we don't orphan them from
every phonetic bucket -- instead we phonetic-encode the leading 1-2
significant tokens of the title (the words most likely to carry a
brand/product-line name in this catalog, e.g. "quickbooks 2007" ->
encode "quickbooks") and use that as the blocking key instead. The
same leading-token fallback key is *also* computed for TableA (in
addition to its manufacturer key) so that a TableB row falling back to
title-token phonetic still has a matching key space on the TableA
side to pair against.

Because a bare phonetic-code match is coarse (Soundex in particular
collapses many distinct names to short 4-character codes, so buckets
can be large), every pair generated by a shared phonetic key is scored
by a secondary within-block title-similarity check (rapidfuzz
token_set_ratio on normalized titles) and only pairs clearing a
minimum similarity floor are kept. Pairs are additionally ranked by
this score (plus a manufacturer-exact-match bonus and an
exact-vs-fallback-key distinction) and truncated to a target cap that
leaves headroom for the ensemble merge.

Per this task's rules, 100_matches.pkl is used only to measure a local
proxy recall number as we tune -- those 100 pairs are NOT excluded
from this strategy's output (candidates_phonetic.pkl). Exclusion
happens once, later, at the final ensemble/submission step.

Output: candidates_phonetic.pkl -- a plain pickle of the Python `set`
of (id_a, id_b) tuples (id_a from TableA, id_b from TableB, tracked
explicitly and NEVER sorted/swapped, since the two tables' ids share
the same 0..N integer namespace).
"""

import pickle
import re
from collections import defaultdict

import pandas as pd

try:
    from rapidfuzz import fuzz
    HAVE_RAPIDFUZZ = True
except ImportError:
    HAVE_RAPIDFUZZ = False

try:
    import jellyfish
    HAVE_JELLYFISH = True
except ImportError:
    HAVE_JELLYFISH = False


# --------------------------------------------------------------------------
# Fallback manual Soundex implementation (used only if jellyfish is
# unavailable in the runtime environment -- it IS available here, but the
# fallback is kept so this script is portable / robust).
# --------------------------------------------------------------------------
_SOUNDEX_CODES = {
    'b': '1', 'f': '1', 'p': '1', 'v': '1',
    'c': '2', 'g': '2', 'j': '2', 'k': '2', 'q': '2', 's': '2', 'x': '2', 'z': '2',
    'd': '3', 't': '3',
    'l': '4',
    'm': '5', 'n': '5',
    'r': '6',
}


def manual_soundex(word: str) -> str:
    word = re.sub(r'[^a-z]', '', word.lower())
    if not word:
        return ''
    first_letter = word[0]
    codes = [_SOUNDEX_CODES.get(c, '0') for c in word]
    # drop the first letter's own code duplication step, then collapse
    # adjacent duplicates, drop zeros, pad/truncate to 4 chars (letter+3).
    result = [first_letter.upper()]
    prev_code = codes[0]
    for c in codes[1:]:
        if c != prev_code:
            if c != '0':
                result.append(c)
        prev_code = c
    code = ''.join(result)
    return (code + '000')[:4]


def soundex(word: str) -> str:
    if not word:
        return ''
    if HAVE_JELLYFISH:
        try:
            return jellyfish.soundex(word)
        except Exception:
            return manual_soundex(word)
    return manual_soundex(word)


def metaphone(word: str) -> str:
    if not word:
        return ''
    if HAVE_JELLYFISH:
        try:
            return jellyfish.metaphone(word)
        except Exception:
            return ''
    return ''


# --------------------------------------------------------------------------
# Text normalization helpers
# --------------------------------------------------------------------------
STOPWORDS = {
    'the', 'and', 'for', 'with', 'of', 'a', 'an', 'to', 'in', 'on',
    'edition', 'software', 'version', 'inc', 'inc.', 'corp', 'corp.',
    'corporation', 'ltd', 'ltd.', 'llc', 'co', 'co.', 'company',
}


def normalize_text(s):
    if pd.isna(s):
        return ''
    s = str(s).lower()
    s = re.sub(r'[^a-z0-9\s]', ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def significant_tokens(title_norm: str, n=2):
    """Leading significant (non-stopword, alpha, len>=3) tokens of a title."""
    toks = [t for t in title_norm.split() if t.isalpha() and len(t) >= 3 and t not in STOPWORDS]
    return toks[:n]


def token_set_sim(a_title_norm, b_title_norm):
    if HAVE_RAPIDFUZZ:
        return fuzz.token_set_ratio(a_title_norm, b_title_norm) / 100.0
    # fallback: simple Jaccard on tokens
    ta, tb = set(a_title_norm.split()), set(b_title_norm.split())
    if not ta or not tb:
        return 0.0
    return len(ta & tb) / len(ta | tb)


def phonetic_keys_for_manufacturer(manu_norm: str):
    """Return set of phonetic keys derived from a manufacturer string,
    one per significant word (so multi-word manufacturers like
    'intuit inc' contribute a key for 'intuit')."""
    keys = set()
    for tok in manu_norm.split():
        if tok in STOPWORDS or len(tok) < 2:
            continue
        sx = soundex(tok)
        mp = metaphone(tok)
        if sx:
            keys.add(('SX', sx))
        if mp:
            keys.add(('MP', mp))
    return keys


def phonetic_keys_for_title_fallback(title_norm: str):
    keys = set()
    for tok in significant_tokens(title_norm, n=2):
        sx = soundex(tok)
        mp = metaphone(tok)
        if sx:
            keys.add(('SX', sx))
        if mp:
            keys.add(('MP', mp))
    return keys


def main():
    print(f"jellyfish available: {HAVE_JELLYFISH}, rapidfuzz available: {HAVE_RAPIDFUZZ}")

    df_a = pd.read_csv('tableA.csv')
    df_b = pd.read_csv('tableB.csv')
    print(f"TableA: {len(df_a)} rows, TableB: {len(df_b)} rows")

    df_a['title_norm'] = df_a['title'].apply(normalize_text)
    df_b['title_norm'] = df_b['title'].apply(normalize_text)
    df_a['manu_norm'] = df_a['manufacturer'].apply(normalize_text)
    df_b['manu_norm'] = df_b['manufacturer'].apply(normalize_text)

    # --- Build phonetic key -> record-id index for each table ---------
    # Each record contributes keys from manufacturer (if present) AND,
    # for TableB rows with no manufacturer (or as an always-on
    # supplementary source for TableA), from the leading title tokens.
    # This lets a TableB row with a real manufacturer match a TableA row
    # via manufacturer phonetics, AND lets a TableB row with NO
    # manufacturer still match via title-leading-token phonetics against
    # TableA's own leading-title-token keys.

    a_index = defaultdict(set)   # key -> set of id_a  (manufacturer-based)
    a_index_title = defaultdict(set)  # key -> set of id_a (title-leading-token based)
    b_index = defaultdict(set)   # key -> set of id_b  (manufacturer-based)
    b_index_title = defaultdict(set)  # key -> set of id_b (title-leading-token based)

    for _, row in df_a.iterrows():
        rid = row['id']
        if row['manu_norm']:
            for k in phonetic_keys_for_manufacturer(row['manu_norm']):
                a_index[k].add(rid)
        for k in phonetic_keys_for_title_fallback(row['title_norm']):
            a_index_title[k].add(rid)

    n_b_has_manu = 0
    for _, row in df_b.iterrows():
        rid = row['id']
        if row['manu_norm']:
            n_b_has_manu += 1
            for k in phonetic_keys_for_manufacturer(row['manu_norm']):
                b_index[k].add(rid)
        else:
            for k in phonetic_keys_for_title_fallback(row['title_norm']):
                b_index_title[k].add(rid)

    print(f"TableB rows with manufacturer: {n_b_has_manu}/{len(df_b)}")
    print(f"Phonetic keys -- A manu: {len(a_index)}, A title-fallback: {len(a_index_title)}, "
          f"B manu: {len(b_index)}, B title-fallback: {len(b_index_title)}")

    title_a = dict(zip(df_a['id'], df_a['title_norm']))
    title_b = dict(zip(df_b['id'], df_b['title_norm']))
    manu_a = dict(zip(df_a['id'], df_a['manu_norm']))
    manu_b = dict(zip(df_b['id'], df_b['manu_norm']))

    # --- Generate raw pair candidates from shared phonetic keys --------
    # Pairing sources:
    #   1. A-manufacturer  x  B-manufacturer   (strongest: both real brands)
    #   2. A-manufacturer  x  B-title-fallback (B has no manufacturer; A does)
    #   3. A-title-fallback x  B-manufacturer  (symmetric case)
    #   4. A-title-fallback x  B-title-fallback (both weak signal, but still
    #      catches cases where neither table's manufacturer field was useful)
    raw_pairs = {}  # (id_a, id_b) -> source tag (for scoring bonus)

    def add_pairs(idx_a, idx_b, tag):
        for key, ids_a in idx_a.items():
            ids_b = idx_b.get(key)
            if not ids_b:
                continue
            for ida in ids_a:
                for idb in ids_b:
                    prev = raw_pairs.get((ida, idb))
                    if prev is None or tag < prev:
                        raw_pairs[(ida, idb)] = tag

    add_pairs(a_index, b_index, 0)             # manu x manu (best)
    add_pairs(a_index, b_index_title, 1)       # manu x title-fallback
    add_pairs(a_index_title, b_index, 1)       # title-fallback x manu
    add_pairs(a_index_title, b_index_title, 2)  # title-fallback x title-fallback

    print(f"Raw phonetic-bucket pairs (pre-similarity-filter): {len(raw_pairs)}")

    # --- Within-block title similarity scoring + filtering --------------
    MIN_SIM = 0.35  # floor to cut coarse Soundex-bucket noise
    scored = []
    for (ida, idb), tag in raw_pairs.items():
        ta, tb = title_a.get(ida, ''), title_b.get(idb, '')
        sim = token_set_sim(ta, tb)
        if sim < MIN_SIM:
            continue
        manu_bonus = 0.0
        ma, mb = manu_a.get(ida, ''), manu_b.get(idb, '')
        if ma and mb and ma == mb:
            manu_bonus = 0.25
        elif ma and mb:
            # both present but not identical -- still check phonetic agreement
            ka = phonetic_keys_for_manufacturer(ma)
            kb = phonetic_keys_for_manufacturer(mb)
            if ka & kb:
                manu_bonus = 0.15
        tag_bonus = {0: 0.15, 1: 0.05, 2: 0.0}[tag]
        score = sim + manu_bonus + tag_bonus
        scored.append((score, ida, idb))

    scored.sort(key=lambda x: -x[0])
    print(f"Pairs surviving similarity floor ({MIN_SIM}): {len(scored)}")

    CAP = 2800
    top = scored[:CAP]
    candidates = set((ida, idb) for _, ida, idb in top)
    print(f"Final candidate count (capped at {CAP}): {len(candidates)}")

    with open('candidates_phonetic.pkl', 'wb') as f:
        pickle.dump(candidates, f)

    # --- Proxy recall against the 100 known matches ---------------------
    try:
        with open('100_matches.pkl', 'rb') as f:
            known = pickle.load(f)
        if isinstance(known, dict):
            known_pairs = set(known.keys()) if all(isinstance(k, tuple) for k in known.keys()) else set(known.values())
        else:
            known_pairs = set(known)
        found = known_pairs & candidates
        recall = len(found) / len(known_pairs) if known_pairs else float('nan')
        print(f"Known matches: {len(known_pairs)}, found in candidates: {len(found)}, "
              f"proxy recall: {recall:.3f}")

        missed = known_pairs - candidates
        if missed:
            print(f"Missed {len(missed)} known matches. Sample of up to 5:")
            for ida, idb in list(missed)[:5]:
                print(f"  ({ida},{idb}) A='{title_a.get(ida,'?')}' manu='{manu_a.get(ida,'')}' "
                      f"| B='{title_b.get(idb,'?')}' manu='{manu_b.get(idb,'')}'")
    except FileNotFoundError:
        print("100_matches.pkl not found -- skipping proxy recall computation.")


if __name__ == '__main__':
    main()
